// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module generic_fmax_double_s (
        ap_ready,
        x,
        y,
        ap_return
);


output   ap_ready;
input  [63:0] x;
input  [63:0] y;
output  [63:0] ap_return;

wire   [63:0] t_V_1_fu_42_p1;
wire   [63:0] t_V_2_fu_68_p1;
wire   [10:0] loc_V_fu_54_p4;
wire   [51:0] loc_V_1_fu_64_p1;
wire   [10:0] loc_V_2_fu_80_p4;
wire   [51:0] loc_V_3_fu_90_p1;
wire   [0:0] tmp_s_fu_100_p2;
wire   [0:0] tmp_29_fu_106_p2;
wire   [0:0] tmp_1_fu_94_p2;
wire   [0:0] tmp_30_fu_112_p2;
wire   [0:0] tmp11_fu_124_p2;
wire   [0:0] tmp10_fu_118_p2;
wire   [0:0] tmp_i_fu_136_p2;
wire   [0:0] tmp_i_17_fu_142_p2;
wire   [0:0] tmp_i1_fu_154_p2;
wire   [0:0] tmp_i1_18_fu_160_p2;
wire   [0:0] p_Result_s_fu_46_p3;
reg   [51:0] p_Result_13_fu_172_p4;
wire   [63:0] p_Result_14_fu_182_p4;
wire   [0:0] ymaggreater_fu_196_p2;
wire   [0:0] ymaggreater_1_fu_202_p2;
wire   [0:0] p_Result_9_fu_72_p3;
wire   [0:0] p_s_fu_208_p3;
wire   [0:0] ymaggreater2_fu_216_p3;
wire   [0:0] or_cond2_fu_130_p2;
wire   [0:0] tmp_57_demorgan_fu_148_p2;
wire   [0:0] sel_tmp_fu_232_p2;
wire   [0:0] sel_tmp1_fu_238_p2;
wire   [0:0] tmp_59_demorgan_fu_166_p2;
wire   [0:0] sel_tmp2_fu_244_p2;
wire   [63:0] res_fu_192_p1;
wire   [63:0] res_1_fu_224_p3;
wire   [0:0] sel_tmp6_demorgan_fu_258_p2;
wire   [0:0] sel_tmp6_fu_264_p2;
wire   [0:0] sel_tmp7_fu_270_p2;
wire   [63:0] res_2_fu_250_p3;
wire   [0:0] sel_tmp11_demorgan_fu_284_p2;
wire   [0:0] sel_tmp3_fu_290_p2;
wire   [0:0] sel_tmp4_fu_296_p2;
wire   [63:0] res_4_fu_276_p3;
wire   [63:0] res_5_fu_302_p3;

assign ap_ready = 1'b1;

assign ap_return = ((or_cond2_fu_130_p2[0:0] === 1'b1) ? y : res_5_fu_302_p3);

assign loc_V_1_fu_64_p1 = t_V_1_fu_42_p1[51:0];

assign loc_V_2_fu_80_p4 = {{t_V_2_fu_68_p1[62:52]}};

assign loc_V_3_fu_90_p1 = t_V_2_fu_68_p1[51:0];

assign loc_V_fu_54_p4 = {{t_V_1_fu_42_p1[62:52]}};

assign or_cond2_fu_130_p2 = (tmp11_fu_124_p2 & tmp10_fu_118_p2);

always @ (*) begin
    p_Result_13_fu_172_p4 = loc_V_1_fu_64_p1;
    p_Result_13_fu_172_p4[32'd51] = |(1'd1);
end

assign p_Result_14_fu_182_p4 = {{{p_Result_s_fu_46_p3}, {11'd2047}}, {p_Result_13_fu_172_p4}};

assign p_Result_9_fu_72_p3 = t_V_2_fu_68_p1[32'd63];

assign p_Result_s_fu_46_p3 = t_V_1_fu_42_p1[32'd63];

assign p_s_fu_208_p3 = ((p_Result_s_fu_46_p3[0:0] === 1'b1) ? ymaggreater_1_fu_202_p2 : ymaggreater_fu_196_p2);

assign res_1_fu_224_p3 = ((ymaggreater2_fu_216_p3[0:0] === 1'b1) ? y : x);

assign res_2_fu_250_p3 = ((sel_tmp2_fu_244_p2[0:0] === 1'b1) ? res_fu_192_p1 : res_1_fu_224_p3);

assign res_4_fu_276_p3 = ((sel_tmp7_fu_270_p2[0:0] === 1'b1) ? y : res_2_fu_250_p3);

assign res_5_fu_302_p3 = ((sel_tmp4_fu_296_p2[0:0] === 1'b1) ? x : res_4_fu_276_p3);

assign res_fu_192_p1 = p_Result_14_fu_182_p4;

assign sel_tmp11_demorgan_fu_284_p2 = (tmp_57_demorgan_fu_148_p2 | or_cond2_fu_130_p2);

assign sel_tmp1_fu_238_p2 = (tmp_57_demorgan_fu_148_p2 & sel_tmp_fu_232_p2);

assign sel_tmp2_fu_244_p2 = (tmp_59_demorgan_fu_166_p2 & sel_tmp1_fu_238_p2);

assign sel_tmp3_fu_290_p2 = (sel_tmp11_demorgan_fu_284_p2 ^ 1'd1);

assign sel_tmp4_fu_296_p2 = (tmp_59_demorgan_fu_166_p2 & sel_tmp3_fu_290_p2);

assign sel_tmp6_demorgan_fu_258_p2 = (tmp_i1_fu_154_p2 & tmp_i1_18_fu_160_p2);

assign sel_tmp6_fu_264_p2 = (sel_tmp6_demorgan_fu_258_p2 ^ 1'd1);

assign sel_tmp7_fu_270_p2 = (sel_tmp6_fu_264_p2 & sel_tmp1_fu_238_p2);

assign sel_tmp_fu_232_p2 = (or_cond2_fu_130_p2 ^ 1'd1);

assign t_V_1_fu_42_p1 = x;

assign t_V_2_fu_68_p1 = y;

assign tmp10_fu_118_p2 = (tmp_s_fu_100_p2 & tmp_29_fu_106_p2);

assign tmp11_fu_124_p2 = (tmp_30_fu_112_p2 & tmp_1_fu_94_p2);

assign tmp_1_fu_94_p2 = ((loc_V_fu_54_p4 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_29_fu_106_p2 = ((loc_V_2_fu_80_p4 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_30_fu_112_p2 = ((loc_V_3_fu_90_p1 == 52'd0) ? 1'b1 : 1'b0);

assign tmp_57_demorgan_fu_148_p2 = (tmp_i_fu_136_p2 & tmp_i_17_fu_142_p2);

assign tmp_59_demorgan_fu_166_p2 = (tmp_i1_fu_154_p2 & tmp_i1_18_fu_160_p2);

assign tmp_i1_18_fu_160_p2 = ((loc_V_3_fu_90_p1 != 52'd0) ? 1'b1 : 1'b0);

assign tmp_i1_fu_154_p2 = ((loc_V_2_fu_80_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign tmp_i_17_fu_142_p2 = ((loc_V_1_fu_64_p1 != 52'd0) ? 1'b1 : 1'b0);

assign tmp_i_fu_136_p2 = ((loc_V_fu_54_p4 == 11'd2047) ? 1'b1 : 1'b0);

assign tmp_s_fu_100_p2 = ((loc_V_1_fu_64_p1 == 52'd0) ? 1'b1 : 1'b0);

assign ymaggreater2_fu_216_p3 = ((p_Result_9_fu_72_p3[0:0] === 1'b1) ? p_s_fu_208_p3 : ymaggreater_fu_196_p2);

assign ymaggreater_1_fu_202_p2 = (ymaggreater_fu_196_p2 ^ 1'd1);

assign ymaggreater_fu_196_p2 = (($signed(t_V_1_fu_42_p1) < $signed(t_V_2_fu_68_p1)) ? 1'b1 : 1'b0);

endmodule //generic_fmax_double_s
